
<html>
	<head>
 	<title></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/style.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/foundation/stylesheets/foundation.css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/foundation/javascripts/app.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/foundation/javascripts/foundation.js" /></script>
	</head>
	<body>
		<div class="container" >
			<!-- Header -->
			<div class="row">
				<div class="twelve columns header">
					<h3>tmedical software</h3>
					<p>This is version 0.1.0</p>
					<hr>
				</div>
			</div>
			<!-- Content -->
			<div class="row">
				<!-- Sidebar -->
				<div class="three columns">
					side bar - for menu items
				</div>
				<!-- content -->
				<div class="nine columns content">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
			<!-- Footer -->
			<div class="footer">
			<hr>
				<p>a product from touchwire software 2011</p>
			</div>
		</div>
		
	</body>
</html>
