
<html>
	<head>
 	<title></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/style.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/foundation/stylesheets/foundation.css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/foundation/javascripts/app.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/foundation/javascripts/foundation.js" /></script>
	</head>
	<body>
	<!-- Header -->
			<div >
				<div class="header">
					<img src="<?php echo $this->baseUrl();?>/public/images/logo-sm.gif">
					
				</div>
			</div>
		<div class="container" >
			
			<!-- Content -->
			<div class="row">
				<!-- Sidebar -->
				<div class="three columns">
					side bar - for menu items
				</div>
				<!-- content -->
				<div class="nine columns content">
					<?php echo $this->layout()->content; ?>
				</div>
			</div>
			<!-- Footer -->
			<div class="footer">
			<div class="right"><img src="<?php echo $this->baseUrl();?>/public/images/logo-xsm.gif" align="absmiddle"></div>
				<p>a product from touch wire software solutions 2011</p>
			</div>
		</div>
		
	</body>
</html>
